### ISSUE TITLE
can't download project file

### ISSUE THREAD

**Issue by qingfeng-zhang** [dyh/unbox_yolov5_deepsort_counting#1]
only can get unbox_yolov5_deepsort_counting-main .zip instead of the project file, can you please check why?

**Comment by dyh** [comment]
试试这个：https://github.com/dyh/unbox_yolov5_deepsort_counting/releases/tag/v0.1

**Comment by jiangyuanlin01** [comment]
> 试试这个：[https](https://github.com/dyh/unbox_yolov5_deepsort_counting/releases/tag/v0.1) : [//github.com/dyh/unbox_yolov5_deepsort_counting/releases/tag/v0.1](https://github.com/dyh/unbox_yolov5_deepsort_counting/releases/tag/v0.1)

这个链接还是访问不到，一直是404
