### ISSUE TITLE
撞线

### ISSUE THREAD

**Issue by Recallmym** [dyh/unbox_yolov5_deepsort_counting#14]
撞线位置怎么设置啊

**Comment by dyh** [comment]
默认是 南/北 方向检测，若要检测不同位置和方向，可在 main.py 文件第13行和21行，修改2个polygon的点。

**Comment by Recallmym** [comment]
自己的视频  然后怎么确定 撞线的坐标啊

**Comment by Recallmym** [comment]
用的什么工具 确定的 可以告诉我一下吗 大佬0.0

**Comment by dyh** [comment]
可以直接 写 x、y 坐标。你改2个点试试就明白了。：）
