### ISSUE TITLE
检测不到目标问题

### ISSUE THREAD

**Issue by vvxt** [dyh/unbox_yolov5_deepsort_counting#16]
请问能正常运行不报错，但是一直没有bbox返回是什么问题导致的？

**Comment by dyh** [comment]
断点看看yolov5 的bbox返回值有没有值。

**Comment by vvxt** [comment]
看了，没有返回值，len(bboxes)一直为0。

**Comment by vvxt** [comment]
> 断点看看yolov5 的bbox返回值有没有值。
> […](#)
> 在 2021年5月13日，18:54，vvxt ***@***.***> 写道： ﻿ 请问能正常运行不报错，但是一直没有bbox返回是什么问题导致的？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

看了，没有返回值，len(bboxes)一直为0。

**Comment by dyh** [comment]
那您先到yolov5官网，先把它调通。

**Comment by vvxt** [comment]
> 那您先到yolov5官网，先把它调通。
> […](#)
> 在 2021年5月14日，10:44，vvxt ***@***.***> 写道： ﻿ 断点看看yolov5 的bbox返回值有没有值。 … 在 2021年5月13日，18:54，vvxt @.***> 写道： ﻿ 请问能正常运行不报错，但是一直没有bbox返回是什么问题导致的？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 看了，没有返回值，len(bboxes)一直为0。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢！
