### ISSUE TITLE
视频每一帧的时间

### ISSUE THREAD

**Issue by Onebing** [dyh/unbox_yolov5_deepsort_counting#17]
您好！我想问一下咱们一帧检测的时间是多少，用的GPU是什么配置，加入检测时间不能没有视频快的话怎么应用到实时检测呢

**Comment by dyh** [comment]
您好，看情况。
1、如果流量小，短暂的延迟，后期可以追回来。
2、如果流量大，可以降低分辨率，减小检测区域，用更小的模型，最后再用更好的硬件。
3、我的实际应用，人车检测，流量不大，平均1小时100人。i7 8700，rtx2060，rtsp视频分辨率1440p，官方yolov5x+本项目使用的deepsort，勉强够用，我感觉检测的时候每秒5-10帧。

**Comment by Onebing** [comment]
> 您好，看情况。
> 1、如果流量小，短暂的延迟，后期可以追回来。
> 2、如果流量大，可以降低分辨率，减小检测区域，用更小的模型，最后再用更好的硬件。
> 3、我的实际应用，人车检测，流量不大，平均1小时100人。i7 8700，rtx2060，rtsp视频分辨率1440p，官方yolov5x+本项目使用的deepsort，勉强够用，我感觉检测的时候每秒5-10帧。

好的谢了，我具体测试的时候也差不多是这个速度
