### ISSUE TITLE
激活虚拟环境

### ISSUE THREAD

**Issue by HogeReset** [dyh/unbox_yolov5_deepsort_counting#31]
第4步，激活虚拟环境一直过不去，还有第6步安装版本不知道怎么查询。
![01](https://user-images.githubusercontent.com/48879539/151656273-bf48fe94-057f-418b-b315-7d7680c0a955.jpg)

**Comment by hecigsape** [comment]
verifica posiblemente no esta en la carpeta "bin" pero si en la carpeta "Scripts" prueba $ source venv/Scripts/activate
