### ISSUE TITLE
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by molua** [dyh/unbox_yolov5_deepsort_counting#38]
我将这个项目直接git到google colab上运行显示这个错误

Python 3.7.13
torch 1.12.0+cu113

**Comment by dyh** [comment]
pytorch版本太高了，试试 torch 1.10。

**Comment by youyuanyi** [comment]
修改upsamping.py的Upsampling类的forward函数：
    def forward(self, input: Tensor) -> Tensor:
        # return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
        #                      recompute_scale_factor=self.recompute_scale_factor)

        return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)

**Comment by Liu-Yin** [comment]
看起来像是torch版本不匹配，同建议降低一下torch版本
