### ISSUE TITLE
怎麽使用自己的訓練好的模型？

### ISSUE THREAD

**Issue by manmo-hut** [dyh/unbox_yolov5_deepsort_counting#4]
我有訓練自己的模型，4個模型都有做訓練，但當我放入自己的模型且在models中添加了關於這個模型的yaml檔案后，在更改了detector.py中self.weights的路徑后出現錯誤
AttributeError: Can't get attribute 'C3' on <module 'models.common' from 'C:\\Users\\User\\Desktop\\yolov5\\unbox_yolov5_deepsort_counting\\models\\common.py'>
請問這個要如何解決？

**Comment by manmo-hut** [comment]
我也把yolo.py中61行的cfg='yolov5m.yaml'改成自己的模型yaml

**Comment by dyh** [comment]
https://github.com/ultralytics/yolov5/issues/1855

**Comment by CB-Jack-S** [comment]
相同的问题请问题主解决了没有？上面的帖子里提到的说是代码未更新并不是很明白

**Comment by dyh** [comment]
@CB-Jack-S  你好，我猜测问题出在yolov5的使用方法，建议一步一步来排查。
先用yolov5官方demo跑通自己训练的模型，确认yolov5没问题之后，再使用deepSORT检测bbox。

**Comment by manmo-hut** [comment]
找到問題了，因爲yolov5版本問題，更新4.0后就可以了

**Comment by CB-Jack-S** [comment]
谢谢  我也已经解决了  用yolov5中common文件中部分代码替换了现在的common就可以跑通啦~

**Comment by dyh** [comment]
谢谢告知。

**Comment by dyh** [comment]
yolov5更新好快。
