### ISSUE TITLE
 pkg-resources 依赖安装错误

### ISSUE THREAD

**Issue by zaiwuwu** [dyh/unbox_yolov5_deepsort_counting#52]
ERROR: Could not find a version that satisfies the requirement pkg-resources (from versions: none)
ERROR: No matching distribution found for pkg-resources
请教一下遇到这种情况是不是就需要重新安装与依赖适配的python版本的虚拟环境？

**Comment by shuaiqidenanhai** [comment]
hi can you tell me how to solve it? Thanks

**Comment by shuaiqidenanhai** [comment]
@zaiwuwu
