### ISSUE TITLE
opencv

### ISSUE THREAD

**Issue by jiangyuanlin01** [dyh/unbox_yolov5_deepsort_counting#8]
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-s8zh4qlk/opencv/modules/highgui/src/window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

**Comment by dyh** [comment]
请百度。
